name: Deploy Frontend Sigescon

on:
  workflow_dispatch:
  push:
    branches: [ main, homologation ]

jobs:
  deploy-homolog:
    name: Deploy Homologação
    if: github.ref == 'refs/heads/homologation'
    runs-on: [ self-hosted, homologation ]
    steps:
      - name: Executar script de deploy de homologação
        run: /home/ginf/scripts/sigescon/deploy-front.sh ${{ github.ref_name }}

  deploy-prod:
    name: Deploy Produção
    if: github.ref == 'refs/heads/main'
    runs-on: [ self-hosted, production ]
    steps:
      - name: Executar script de deploy de produção
        run: /home/ginf/scripts/sigescon/deploy-sigescon-front.sh ${{ github.ref_name }}