name: Deploy Frontend

on:
  push:
    branches:
      - homologation
      - main
  workflow_dispatch:

env:
  SISTEMA: "sigescon"

jobs:
  deploy-homolog:
    name: Deploy Homologação
    if: github.ref_name == 'homologation'
    runs-on: [self-hosted, homologation]
    steps:
      - name: Executar Deploy em Homologação
        run: |
          /home/ginf/scripts/${{ env.SISTEMA }}/deploy-front.sh ${{ github.ref_name }}

  deploy-prod:
    name: Deploy Produção
    if: github.ref_name == 'main'
    runs-on: [self-hosted, production]
    steps:
      - name: Executar Deploy em Produção
        run: |
          /home/ginf/scripts/deploy-front.sh ${{ github.ref_name }}