name: Deploy Frontend

on:
  workflow_dispatch:
  push:
    branches: [ homologation, main ]

jobs:
  deploy-homolog:
    name: Deploy Homologação
    if: github.ref == 'refs/heads/homologation'
    runs-on: [ self-hosted, homologation ]
    steps:
      - name: Executar script de deploy de homologação
        run: /home/ginf/scripts/sigescon/deploy-front.sh

  deploy-prod:
    name: Deploy Produção
    if: github.ref == 'refs/heads/main'
    runs-on: [ self-hosted, production ]
    steps:
      - name: Executar script de deploy de produção
        run: ~/deploy-front.sh